<?php

namespace AGIL\ProfileBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilSkillRepository extends EntityRepository
{
}
