<?php

namespace AGIL\HallBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilPhotoRepository extends EntityRepository
{
}
