<?php

namespace AGIL\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgilUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilUserRepository extends EntityRepository
{
}
