<?php

namespace AGIL\DefaultBundle\Repository;

/**
 * AgilUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilUserRepository extends \Doctrine\ORM\EntityRepository
{
}
