<?php

namespace AGIL\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilTagRepository extends EntityRepository
{
}
