<?php

namespace AGIL\OfferBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilOfferRepository extends EntityRepository
{
}
