<?php

namespace AGIL\ChatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilChatTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilChatTableRepository extends EntityRepository
{
}
