<?php

namespace AGIL\ChatBundle\Repository;

/**
 * AgilChatMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilChatMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
