<?php

namespace AGIL\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilForumCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilForumCategoryRepository extends EntityRepository
{
}
