<?php

namespace AGIL\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilForumAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilForumAnswerRepository extends EntityRepository
{
}
