<?php

namespace AGIL\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilForumCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilForumCategoryRepository extends EntityRepository
{

    /**
     * Redéfinition de la méthode findAll de base, afin de trier
     * les résultats par ordre alphabétique croissant.
     * @return array
     */
    public function findAll()
    {
        return $this->findBy(array(), array('forumCategoryName' => 'ASC'));
    }


    public function getCountSubjectsInCategory($idCategory){

        $query = $this->_em->createQueryBuilder();

        $query->select('COUNT(sub.forumSubjectId) as cnt')
            ->from('AGIL\ForumBundle\Entity\AgilForumSubject','sub')
            ->where('sub.category = ?1')
        ;

        $query->setParameter(1,$idCategory);

        return $query->getQuery()->getSingleScalarResult();

    }

}
