<?php

namespace AGIL\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AgilForumAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilForumAnswerRepository extends EntityRepository
{

    /**
     * @param int $page
     * @param int $maxperpage
     * @param $idSubject
     * @return Paginator
     */
    public function getAnswersBySubject($page=1, $maxperpage=10,$idSubject){

        $query = $this->_em->createQueryBuilder();

        $query->select('ans.forumAnswerPostDate','ans.forumAnswerId',
            'ans.forumAnswerText','ans','us.username','us.id','us.roles','us.userProfilePictureUrl','us')
            ->from('AGIL\ForumBundle\Entity\AgilForumAnswer','ans')
            ->leftJoin('ans.user','us')
            ->where('ans.subject = ?1')
            ->orderBy('ans.forumAnswerPostDate','asc')
        ;

        $query->setParameter(1,$idSubject);

        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage)->getQuery();

        return new Paginator($query);

    }
}
