<?php

namespace AGIL\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilForumDeletedReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilForumDeletedReasonRepository extends EntityRepository
{
}
