<?php

namespace AGIL\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgilForumCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgilForumCategoryRepository extends EntityRepository
{

    /**
     * Redéfinition de la méthode findAll de base, afin de trier
     * les résultats par ordre alphabétique croissant.
     * @return array
     */
    public function findAll()
    {
        return $this->findBy(array(), array('forumCategoryName' => 'ASC'));
    }

}
